// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzjurcpcnituhpucrizb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16anVyY3Bjbml0dWhwdWNyaXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTAyNjEsImV4cCI6MjA2MDIyNjI2MX0.85RKqoJcyJjv8LcM9kPrCCVo40d3c4SG_guOa6Z6R20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);